version: 2.1

jobs:
  test-and-build:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.29.0

    resource_class: large

    steps:
      - checkout

      - run:
          name: Verify Flutter version
          command: flutter --version

      - restore_cache:
          keys:
            - flutter-packages-v1-{{ checksum "pubspec.lock" }}
            - flutter-packages-v1-

      - run:
          name: Install dependencies
          command: flutter pub get

      - save_cache:
          key: flutter-packages-v1-{{ checksum "pubspec.lock" }}
          paths:
            - ~/.pub-cache

      - run:
          name: Analyze Flutter code
          command: flutter analyze

      - run:
          name: Run Flutter tests
          command: flutter test

      - run:
          name: Build Android APK
          command: flutter build apk --release

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: Flex-Facility-App.apk

workflows:
  flexapp-android-ci:
    jobs:
      - test-and-build
